import Head from 'next/head'
import styles from '../styles/Home.module.css'
import GridCardsComponent from './components/GridCardsComponent'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Desafio Bud</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.title}>Olá pessoal!</div>
        <p className={styles.description}>
          Me chamo Ricardo Dias Martins, nesse projeto apresento resposta do desafio de programação.
        </p>
        <div className={styles.grid}>
          <GridCardsComponent />
        </div>
      </main>
    </div>
  )
}
